[package]
name = "ncursesw-win"
version = "0.2.1"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
edition = "2018"
description = "An extension wrapper around the ncursesw TUI library (ncurses)"
repository = "https://github.com/narfit66/ncursesw-win-rs"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"

[workspace]

[dependencies]
lazy_static = "1.3.0"
strum = "0.16.0"
strum_macros = "0.16.0"

[dependencies.ncursesw]
version = "0.3.0"
features = []
#features = ["key_resize_as_error", "key_event_as_error"]

[dev-dependencies]
ascii = "0.9.1"

[patch.crates-io]
ncursesw = { git = "https://github.com/narfit66/ncursesw-rs" }
#ncursesw = { path = "../ncursesw-rs" }

[lib]
name = "ncurseswwin"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
