[package]
name = "ncursesw-win"
version = "0.3.0"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
edition = "2018"
description = "An extension wrapper around the ncursesw TUI library (ncurses)"
repository = "https://github.com/narfit66/ncursesw-win-rs"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"

[workspace]

[dependencies]
ncursesw = "0.3.0"
custom_error = "1.6.0"
lazy_static = "1.3.0"
strum = "0.16.0"
strum_macros = "0.16.0"

[dev-dependencies]
ascii = "0.9.1"
rand = "0.7"

[patch.crates-io]
ncursesw = { git = "https://github.com/narfit66/ncursesw-rs" }
#ncursesw = { path = "../ncursesw-rs" }

[features]
# conditional compulation of KEY_RESIZE to return as a NCurseswError::KeyResize for getch(), mvgetch(),
# mvwgetch(), wgetch(), get_wch(), mvget_wch(), mvwget_wch() and wget_ch().
key_resize_as_error = []
# conditional compulation of KEY_EVENT to return as a NCurseswError::KeyEvent for getch(), mvgetch(),
# mvwgetch(), wgetch(), get_wch(), mvget_wch(), mvwget_wch() and wget_ch().
key_event_as_error = []

[lib]
name = "ncurseswwin"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
