[package]
name = "ncursesw-win"
version = "0.2.1"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
edition = "2018"
description = "An extension wrapper around the ncursesw TUI library (ncurses)"
repository = "https://github.com/narfit66/ncursesw-win-rs"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"

[workspace]

[dependencies]
ncursesw = "0.3.0"
lazy_static = "1.3.0"

[patch.crates-io]
ncursesw = { git = "https://github.com/narfit66/ncursesw-rs" }
#ncursesw = { path = "../ncursesw-rs" }

[lib]
name = "ncurseswwin"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
