[package]
name = "ncursesw-win"
version = "0.1.3"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
edition = "2018"
description = "An extension wrapper around the ncursesw TUI library (ncurses)"
documentation = "https://docs.rs/ncursesw-win"
homepage = "https://github.com/narfit66/ncursesw-win-rs"
repository = "https://github.com/narfit66/ncursesw-win-rs"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"

[workspace]

[dependencies]
libc = "0.2"
ncursesw = "0.1"
#ncursesw = { git = "https://github.com/narfit66/ncursesw-rs" }
custom_error = "1.6.0"
lazy_static = "1.3.0"

[lib]
name = "ncurseswwin"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
